language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-dist
  - mysql -uroot -e "DROP DATABASE IF EXISTS cake_notifications_test; CREATE DATABASE cake_notifications_test;"

script:
  - sh -c vendor/bin/phpunit
  - sh -c vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=docs ./src ./tests

notifications:
  email: false