language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=docs ./src ./tests; fi"

notifications:
  email: false