language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - sh -c vendor/bin/phpunit
  - sh -c vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=vendor --ignore=docs ./src ./tests

notifications:
  email: false